### ISSUE TITLE
Enhancement: Add Metrics/Tracking operations

### ISSUE THREAD

**Issue by rmusser01** [rmusser01/tldw#235]
Title.
https://github.com/traceloop/openllmetry

**Add Metrics For:**
- [x] video ingestion pipeline
- [x] Audio ingestion pipeline
- [x] Podcast ingestion pipeline
- [x] Ebook ingestion pipeline
- [ ] #357
- [ ] #358
- [x] PDF ingestion pipeline
- [x] Live Recording & transcription pipeline
- [x] Embeddings Management - Creation time, 

**Non-Media Ingestion**
- [ ] Text search pipelines
- [x] RAG Search
- [x] RAG QA search
- [ ] Every chat pipeline
- [ ] #360
- [ ] Viewing Prompt DB
- [ ] Searching prompts DB
- [ ] Metrics

**Comment by rmusser01** [comment]
[v](https://hamel.dev/blog/posts/evals/)

**Comment by rmusser01** [comment]
https://docs.smith.langchain.com/concepts/evaluation#evaluating-a-single-step-of-an-agent
